import 'package:cv_project_team/core/styles/image/app_images.dart';

List<String> alHesn = [
  AppImages.imagesAlhesnH1,
  AppImages.imagesAlhesnH2,
  AppImages.imagesAlhesnH3,
  AppImages.imagesAlhesnH4,
  AppImages.imagesAlhesnH5,
  AppImages.imagesAlhesnH6,
  AppImages.imagesAlhesnH7,
  AppImages.imagesAlhesnH8,
  AppImages.imagesAlhesnH9,
  AppImages.imagesAlhesnH10,
  AppImages.imagesAlhesnH11,
  AppImages.imagesAlhesnH12,
  AppImages.imagesAlhesnH13,
  AppImages.imagesAlhesnH14,
  AppImages.imagesAlhesnH15,
  AppImages.imagesAlhesnH16,
  AppImages.imagesAlhesnH17,
  AppImages.imagesAlhesnH18,
  AppImages.imagesAlhesnH19,
  AppImages.imagesAlhesnH20,
  AppImages.imagesAlhesnH21,
  AppImages.imagesAlhesnH22,
  AppImages.imagesAlhesnH23,
  AppImages.imagesAlhesnH24,
  AppImages.imagesAlhesnH25,
  AppImages.imagesAlhesnH26,
  AppImages.imagesAlhesnH27,
  AppImages.imagesAlhesnH28,
  AppImages.imagesAlhesnH29,
  AppImages.imagesAlhesnH30,
  AppImages.imagesAlhesnH31,
  AppImages.imagesAlhesnH32,
  AppImages.imagesAlhesnH33,
  AppImages.imagesAlhesnH34,
  AppImages.imagesAlhesnH35,
];

List<String> alMadkhal = [
  AppImages.imagesAlmadkhalM1,
  AppImages.imagesAlmadkhalM2,
  AppImages.imagesAlmadkhalM3,
  AppImages.imagesAlmadkhalM4,
  AppImages.imagesAlmadkhalM5,
  AppImages.imagesAlmadkhalM6,
  AppImages.imagesAlmadkhalM7,
  AppImages.imagesAlmadkhalM8,
  AppImages.imagesAlmadkhalM9,
  AppImages.imagesAlmadkhalM10,
  AppImages.imagesAlmadkhalM11,
  AppImages.imagesAlmadkhalM12,
  AppImages.imagesAlmadkhalM13,
  AppImages.imagesAlmadkhalM14,
  AppImages.imagesAlmadkhalM15,
  AppImages.imagesAlmadkhalM16,
];

List<String> alSahn = [
  AppImages.imagesAlsahnS1,
  AppImages.imagesAlsahnS2,
  AppImages.imagesAlsahnS3,
  AppImages.imagesAlsahnS4,
  AppImages.imagesAlsahnS5,
  AppImages.imagesAlsahnS6,
  AppImages.imagesAlsahnS7,
  AppImages.imagesAlsahnS8,
  AppImages.imagesAlsahnS9,
  AppImages.imagesAlsahnS10,
  AppImages.imagesAlsahnS11,
  AppImages.imagesAlsahnS12,
  AppImages.imagesAlsahnS13,
  AppImages.imagesAlsahnS14,
  AppImages.imagesAlsahnS15,
  AppImages.imagesAlsahnS16,
  AppImages.imagesAlsahnS17,
  AppImages.imagesAlsahnS18,
  AppImages.imagesAlsahnS19,
  AppImages.imagesAlsahnS20,
  AppImages.imagesAlsahnS21,
  AppImages.imagesAlsahnS22,
  AppImages.imagesAlsahnS23,
];

List<String> outsideDer = [
  AppImages.imagesOutsideDerOut1,
  AppImages.imagesOutsideDerOut2,
  AppImages.imagesOutsideDerOut3,
  AppImages.imagesOutsideDerOut4,
  AppImages.imagesOutsideDerOut5,
  AppImages.imagesOutsideDerOut6,
  AppImages.imagesOutsideDerOut7,
];

List<String> oldKhoras = [
  AppImages.imagesSalatAlmaaedaMaaeda1,
  AppImages.imagesSalatAlmaaedaMaaeda2,
  AppImages.imagesSalatAlmaaedaMaaeda3,
  AppImages.imagesSalatAlmaaedaMaaeda4,
  AppImages.imagesSalatAlmaaedaMaaeda5,
  AppImages.imagesSalatAlmaaedaMaaeda6,
  AppImages.imagesSalatAlmaaedaMaaeda7,
];

List<String> southHekal = [
  AppImages.imagesSouthHekalHkl1,
  AppImages.imagesSouthHekalHkl2,
  AppImages.imagesSouthHekalHkl3,
  AppImages.imagesSouthHekalHkl4,
  AppImages.imagesSouthHekalHkl5,
  AppImages.imagesSouthHekalHkl6,
  AppImages.imagesSouthHekalHkl7,
  AppImages.imagesSouthHekalHkl8,
];

List<String> northHekal = [
  AppImages.imagesNorthHekalNkl1,
  AppImages.imagesNorthHekalNkl2,
  AppImages.imagesNorthHekalNkl3,
  AppImages.imagesNorthHekalNkl4,
  AppImages.imagesNorthHekalNkl5,
  AppImages.imagesNorthHekalNkl6,
  AppImages.imagesNorthHekalNkl7,
  AppImages.imagesNorthHekalNkl8,
  AppImages.imagesNorthHekalNkl9,
  AppImages.imagesNorthHekalNkl10,
  AppImages.imagesNorthHekalNkl11,
  AppImages.imagesNorthHekalNkl12,
  AppImages.imagesNorthHekalNkl13,
  AppImages.imagesNorthHekalNkl15,
  AppImages.imagesNorthHekalNkl16,
  AppImages.imagesNorthHekalNkl17,
];

List<String> salatAlmaaeda = [
  AppImages.imagesSalatAlmaaedaMaaeda1,
  AppImages.imagesSalatAlmaaedaMaaeda2,
  AppImages.imagesSalatAlmaaedaMaaeda3,
  AppImages.imagesSalatAlmaaedaMaaeda4,
  AppImages.imagesSalatAlmaaedaMaaeda5,
  AppImages.imagesSalatAlmaaedaMaaeda6,
  AppImages.imagesSalatAlmaaedaMaaeda7,
];

List<String> azraa = [
  AppImages.imagesAzraaAz1,
  AppImages.imagesAzraaAz2,
  AppImages.imagesAzraaAz3,
  AppImages.imagesAzraaAz4,
  AppImages.imagesAzraaAz5,
];
